### ISSUE TITLE
Web Browser won't open

### ISSUE THREAD

**Issue by educampos28** [meshtastic/web#36]
After updating my Heltec module to 1.2.65.0adc5ce, the web page doesn't open and returns the following error message

Something went wrong:
a.map is not a function
Try again

**Comment by garthvh** [comment]
The webui is not working properly on 1.2.65 and 1.2 is not receiving any updates, try going down to 1.2.64
